steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--quiet', '--verbosity=debug']

options:
  logging: LEGACY

timeout: "1600s"

#steps:
#- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#  entrypoint: 'bash'
#  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600s && gcloud app deploy']
#options:
#  logging: CLOUD_LOGGING_ONLY
#timeout: "1600s"
